### ISSUE TITLE
有时会出现因Starlight和VoxelMap导致的崩溃

### ISSUE THREAD

**Issue by Glucy-2** [skimitmc/Client#4]
在游戏时和打开VoxelMap地图界面时都有出现
截图：
![5OD_C0B7SX{UM@B5VH0USCP](https://user-images.githubusercontent.com/53287753/129836379-d8e2bc60-292e-44b4-9032-a469ea45e7cd.jpg)
崩溃报告：
````py
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2021/8/18 下午12:06
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.1)
	at com.mamiyaotaru.voxelmap.util.MapChunkCache.isChunkSurroundedByLoaded(MapChunkCache.java:141)
	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.isChunkReady(PersistentMap.java:1098)
	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.handleChangeInWorld(PersistentMap.java:1021)
	at com.mamiyaotaru.voxelmap.util.WorldUpdateListener.notifyObservers(WorldUpdateListener.java:47)
	at net.minecraft.client.render.WorldRenderer.handler$zom000$postScheduleChunkRender(WorldRenderer:8856)
	at net.minecraft.client.render.WorldRenderer.scheduleChunkRender(WorldRenderer:4884)
	at net.minecraft.client.render.WorldRenderer.scheduleBlockRender(WorldRenderer:2569)
	at net.minecraft.client.world.ClientChunkManager.onLightUpdate(ClientChunkManager:168)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.updateVisible(StarLightEngine.java:272)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:455)
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:525)
	at net.minecraft.world.chunk.light.LightingProvider.doLightUpdates(LightingProvider:1102)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1100)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mamiyaotaru.voxelmap.util.MapChunkCache.isChunkSurroundedByLoaded(MapChunkCache.java:141)
	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.isChunkReady(PersistentMap.java:1098)
	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.handleChangeInWorld(PersistentMap.java:1021)
	at com.mamiyaotaru.voxelmap.util.WorldUpdateListener.notifyObservers(WorldUpdateListener.java:47)
	at net.minecraft.class_761.handler$zom000$postScheduleChunkRender(class_761.java:8856)
	at net.minecraft.class_761.method_3295(class_761.java:4884)
	at net.minecraft.class_761.method_8571(class_761.java:2569)
	at net.minecraft.class_631.method_12247(class_631.java:168)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.updateVisible(StarLightEngine.java:272)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:455)
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:525)
	at net.minecraft.class_3568.method_15516(class_3568.java:1102)

-- Affected level --
Details:
	All players: 3 total; [class_746['MAX_XiaoKui'/1595023, l='ClientLevel', x=135.22, y=131.20, z=142.49], class_745['ChengXi123'/1578767, l='ClientLevel', x=96.81, y=154.49, z=53.16], class_745['XZHao02'/1543370, l='ClientLevel', x=132.77, y=130.97, z=140.83]]
	Chunk stats: 1024, 510 F: 1210 L: 0 U: 628
	Level dimension: minecraft:the_nether
	Level spawn location: World: (-43,63,239), Section: (at 5,15,15 in -3,3,14; chunk contains blocks -48,0,224 to -33,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1086532191 game time, 1305651474 day time
	Server brand: fabric (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$cbe000$onCrash(class_310.java:15599)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: replaymod_lang, Default, Default, Fabric Mods, Faithful 1.17.x.zip, 3D.Default.1.17.v1.4.0.zip, XeKr 原版红石显示1.17-V1.zip, Minecraft-Mod-Language-Package-1.16.zip, Masa_汉化资源包V2c [1.12-1.17].zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 16 Windows 10 amd64-64-Bit Compressed References 20210507_34 (JIT enabled, AOT enabled)
OpenJ9   - 1e9235835
OMR      - 7bff18ff5
JCL      - 7a506c7025 based on jdk-16.0.1+9), Eclipse OpenJ9
	Memory: 484510184 bytes (462 MiB) / 1533476864 bytes (1462 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: SuperDisplay Virtual Adapter
	Graphics card #0 vendor: Software by KeloCube
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=3.47.17.59
	Graphics card #1 name: NVIDIA GeForce GTX 750 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1380
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7168
	Graphics card #2 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 4095.00
	Graphics card #2 deviceId: 0x1c03
	Graphics card #2 versionInfo: DriverVersion=30.0.14.7168
	Graphics card #3 name: Intel(R) HD Graphics 630
	Graphics card #3 vendor: Intel Corporation (0x8086)
	Graphics card #3 VRAM (MB): 1024.00
	Graphics card #3 deviceId: 0x5912
	Graphics card #3 versionInfo: DriverVersion=30.0.100.9684
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 65455.07
	Virtual memory used (MB): 39522.20
	Swap memory total (MB): 40960.00
	Swap memory used (MB): 7274.25
	JVM Flags: 10 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jre-16.0.1.9-openj9\lib\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx6144m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		amecsapi: Amecs API 1.1.5+mc21w16a
		appleskin: AppleSkin mc1.17-2.1.0
		architectury: Architectury 2.4.25
		audiooutput: AudioOutput 0.0.4
		authme: Auth Me 1.5.0
		autofish: Autofish 0.9.3
		baritone: Baritone 1.7.0
		bbor: BoundingBoxOutlineReloaded 2.4-1.17.1
		betterf3: BetterF3 1.1.5
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 2.0.0
		bobby: Bobby 2.0.4
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.3.0
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		carpet: Carpet Mod 1.4.45
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.20.0+build.633
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		colormeoutlines: Color Me Outlines 1.0.1
		com_github_wearblackallday_javautils: JavaUtils 1b369d41cd
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		cullleaves: Cull Leaves 2.2.0
		custom-crosshair-mod: Custom Crosshair Mod 1.3.3-fabric
		customskinloader: CustomSkinLoader 14.13-SNAPSHOT-282
		dimthread: DimensionalThreading 1.2.5
		dontdropit: Don't Drop It! 2.3.0+1.17
		dynamicfps: Dynamic FPS 2.0.5
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fabrishot: Fabrishot 1.5.1
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fastfurnace: FastFurnace 1.17-3.0
		fiber: fiber 0.23.0-2
		gbfabrictools: GBfabrictools 1.3.4+1.17
		horseinfo: Horse Info 0.3.0-1.17
		hydrogen: Hydrogen 0.3
		illuminations: Illuminations 1.6.3
		imblocker: IMBlockerFabric 1.0.14
		inventoryhud: Inventory HUD + 3.3.2
		inventoryprofilesnext: Inventory Profiles Next 0.8.6
		invmove: InvMove 1.17-0.0.1-r1
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.1
		itemmodelfix: Item Model Fix 1.0.2+1.17
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		java: Eclipse OpenJ9 VM 16
		krypton: Krypton 0.1.4
		lambdynlights: LambDynamicLights 2.0.2+1.17
		libzoomer: LibZoomer 0.2.1+1.17
		litematica: Litematica 0.0.0-dev.20210713.103711
		lithium: Lithium 0.7.3
		malilib: MaLiLib 0.10.0-dev.24
		masa_gadget_mod: Masa Gadget 1.17-1.1.6
		mcwifipnp: Minecraft WLAN Plug-n-Play 1.4.2
		memoryusagescreen: Memory Usage Screen 1.1
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		modmenu: Mod Menu 2.0.4
		multiconnect: MultiConnect 1.4.12
		multiconnect-api: MultiConnect API 1.4.12
		notenoughcrashes: Not Enough Crashes 3.4.0+1.17
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		orderly: Orderly 2.0.0-alpha.10+custom-1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		quitconfirm: QuitConfirm 1.3
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		replaymod: Replay Mod 1.17.1-2.6.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.0+IRIS2
		sodium-extra: Sodium Extra 0.3.3
		spark: spark 1.6.1
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		torohealth: ToroHealth Damage Indicators 1.17-fabric-6
		tweakeroo: Tweakeroo 0.10.0-dev.20210710.155746
		voxelmap: VoxelMap 1.10.15
		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
		wthit: wthit 3.8.1
	Launched Version: 1.17.1-Fabric 0.11.6
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.68, NVIDIA Corporation
	Window size: 1680x945
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: replaymod_lang (incompatible), bbor, vanilla, Fabric Mods, file/Faithful 1.17.x.zip, file/3D.Default.1.17.v1.4.0.zip, file/XeKr 原版红石显示1.17-V1.zip, file/Minecraft-Mod-Language-Package-1.16.zip (incompatible), file/Masa_汉化资源包V2c [1.12-1.17].zip
	Current Language: 简体中文 (中国)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader), Starlight (starlight), VoxelMap (voxelmap)
````

**Comment by Glucy-2** [comment]
弃用VoxelMap
